Update guava to 32.1.2
With version 28 we intermittently get errors:
 java.lang.NoClassDefFoundError: Could not initialize
 class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl

Presumably this is because guava was compiled with Java 8 and we're
testing with 9+ which moved `sun.reflect` to `sun.unused`.

The latest guava has a javac setting using Java 9, so hoping that
resolves the issue.