Relax FLIM tolerance value: 10e-5 -> 10e-4
Otherwise, macOS on Apple Silicon yields test failures:

[ERROR]   FitTest.testBayesFitImg:168->assertSampleEquals:254 array contents differ at index [2], expected: <0.20058449> but was: <0.2005953>
[ERROR]   FitTest.testBinning:136->assertSampleEquals:254 array contents differ at index [0], expected: <15.917448> but was: <15.917488>
[ERROR]   FitTest.testGlobalFitImg:214->assertSampleEquals:254 array contents differ at index [3], expected: <4.498526> but was: <4.498537>
[ERROR]   FitTest.testRLDFitImg:120->assertSampleEquals:254 array contents differ at index [3], expected: <4.498526> but was: <4.498537>

Might be the same root cause as flimlib/flimj-ops#18.